title: Tobias Grott
description: My Personal Blog
author: Tobias Grott
logo: /static/img/avatar.png
github: https://github.com/tobiasgrott

baseurl: ""
url: "https://tobiasgrott.github.io"

disqus_shortname: tobiasgrott
#google_analytics: UA-72862926-1

share:
  twitter_username: tobiasgrott
  #fb_appid: 000000000000


enableTags: true
tagarray: [spring,code-style,test]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
future: false
