title: Tobias Grott
description: My Personal Blog
author: Tobias Grott
logo: /blog/static/img/avatar.png
github: https://github.com/tobiasgrott

baseurl: "/blog"
url: "https://tobiasgrott.github.io/blog"

disqus_shortname: tobiasgrott
google_analytics: UA-72862926-1

share:
  twitter_username: tobiasgrott
  fb_appid: 000000000000


enableTags: true
tagarray: [spring,code-style]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
